name: ilmplanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  syncfusion_flutter_pdf: ^31.1.19
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.3
  syncfusion_flutter_pdfviewer: ^31.1.19
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.3
  flutter_pdfview: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
